DROP TABLE IF EXISTS country_search;
CREATE TABLE country_search
(
  iso_code character varying(2) NOT NULL,
  search text[] NOT NULL,
  CONSTRAINT country_search_pkey PRIMARY KEY (iso_code)
);
INSERT INTO country_search VALUES ('AG', array['antigua & barbuda%']);
INSERT INTO country_search VALUES ('AN', array['netherlands antilles%']);
INSERT INTO country_search VALUES ('AR', array['argentinian%']);
INSERT INTO country_search VALUES ('AT', array['austrian%']);
INSERT INTO country_search VALUES ('AU', array['australian%']);
INSERT INTO country_search VALUES ('BA', array['bosnia & herzegovina%']);
INSERT INTO country_search VALUES ('BE', array['belgian%']);
INSERT INTO country_search VALUES ('BN', array['brunei%']);
INSERT INTO country_search VALUES ('BO', array['bolivia%']);
INSERT INTO country_search VALUES ('BR', array['brazilian%']);
INSERT INTO country_search VALUES ('BS', array['bahamas, the%']);
INSERT INTO country_search VALUES ('CA', array['canadian%']);
INSERT INTO country_search VALUES ('CD', array['congo, democratic republic of the%']);
INSERT INTO country_search VALUES ('CG', array['congo, republic of the%','republic of the congo%']);
INSERT INTO country_search VALUES ('CH', array['swiss%']);
INSERT INTO country_search VALUES ('CN', array['chinese%']);
INSERT INTO country_search VALUES ('CS', array['serbia and montenegro%']);
INSERT INTO country_search VALUES ('CU', array['cuban%']);
INSERT INTO country_search VALUES ('CZ', array['czech%']);
INSERT INTO country_search VALUES ('DE', array['german%']);
INSERT INTO country_search VALUES ('DK', array['danish%']);
INSERT INTO country_search VALUES ('DZ', array['algerian%']);
INSERT INTO country_search VALUES ('EE', array['estonian%']);
INSERT INTO country_search VALUES ('ES', array['spanish%']);
INSERT INTO country_search VALUES ('FI', array['finnish%']);
INSERT INTO country_search VALUES ('FR', array['french%']);
INSERT INTO country_search VALUES ('GB', array['uk %', 'english%', 'british%','scottish%','welsh%']);
INSERT INTO country_search VALUES ('GR', array['greek%']);
INSERT INTO country_search VALUES ('HK', array['hong kong%']);
INSERT INTO country_search VALUES ('HR', array['croatian%']);
INSERT INTO country_search VALUES ('HU', array['hungarian%']);
INSERT INTO country_search VALUES ('ID', array['indonesian%']);
INSERT INTO country_search VALUES ('IE', array['irish%']);
INSERT INTO country_search VALUES ('IL', array['israeli%']);
INSERT INTO country_search VALUES ('IN', array['indian%']);
INSERT INTO country_search VALUES ('IR', array['iranian%','iran%']);
INSERT INTO country_search VALUES ('IS', array['icelandic%']);
INSERT INTO country_search VALUES ('IT', array['italian%']);
INSERT INTO country_search VALUES ('JM', array['jamaican%']);
INSERT INTO country_search VALUES ('JP', array['japanese%']);
INSERT INTO country_search VALUES ('KP', array['north korea%']);
INSERT INTO country_search VALUES ('KR', array['south korean%','south korea%']);
INSERT INTO country_search VALUES ('LV', array['latvian%']);
INSERT INTO country_search VALUES ('MD', array['moldova%']);
INSERT INTO country_search VALUES ('MK', array['macedonia%']);
INSERT INTO country_search VALUES ('MM', array['burma%']);
INSERT INTO country_search VALUES ('MO', array['macau%']);
INSERT INTO country_search VALUES ('MX', array['mexican%']);
INSERT INTO country_search VALUES ('MZ', array['mozambican%']);
INSERT INTO country_search VALUES ('NL', array['dutch%']);
INSERT INTO country_search VALUES ('NO', array['norwegian%']);
INSERT INTO country_search VALUES ('NZ', array['new zealand%']);
INSERT INTO country_search VALUES ('PF', array['clipperton island%']);
INSERT INTO country_search VALUES ('PH', array['filipino%']);
INSERT INTO country_search VALUES ('PK', array['pakistani%']);
INSERT INTO country_search VALUES ('PL', array['polish%']);
INSERT INTO country_search VALUES ('PN', array['pitcairn islands%']);
INSERT INTO country_search VALUES ('PR', array['puerto rican%']);
INSERT INTO country_search VALUES ('PT', array['portugal%']);
INSERT INTO country_search VALUES ('RE', array['reunion%']);
INSERT INTO country_search VALUES ('RO', array['romanian%']);
INSERT INTO country_search VALUES ('RU', array['russian%','russia%']);
INSERT INTO country_search VALUES ('SE', array['swedish%']);
INSERT INTO country_search VALUES ('SG', array['singaporean%']);
INSERT INTO country_search VALUES ('SI', array['slovenian%']);
INSERT INTO country_search VALUES ('SK', array['slovak%']);
INSERT INTO country_search VALUES ('SN', array['senegalese%']);
INSERT INTO country_search VALUES ('SU', array['ussr%']);
INSERT INTO country_search VALUES ('SY', array['syria%']);
INSERT INTO country_search VALUES ('TL', array['east timor%']);
INSERT INTO country_search VALUES ('TR', array['turkish%']);
INSERT INTO country_search VALUES ('TZ', array['tanzania%']);
INSERT INTO country_search VALUES ('UA', array['ukrainian%']);
INSERT INTO country_search VALUES ('UM', array['wake island%','kingman reef%']);
INSERT INTO country_search VALUES ('US', array['us %', 'american%', 'usa %', 'los angeles %', 'san francisco %']);
INSERT INTO country_search VALUES ('VA', array['vatican city%','holy see (vatican city)%']);
INSERT INTO country_search VALUES ('VC', array['saint vincent and the grenadines%']);
INSERT INTO country_search VALUES ('VE', array['venezuela%']);
INSERT INTO country_search VALUES ('VN', array['vietnam%']);
INSERT INTO country_search VALUES ('XC', array['czechoslovakia%']);
INSERT INTO country_search VALUES ('XG', array['german democratic republic%']);
INSERT INTO country_search VALUES ('YU', array['yugoslavia%']);
INSERT INTO country_search VALUES ('ZA', array['south african%']);
